### ISSUE TITLE
Issue with invalid UTF-8 data (related to Vim keystrokes in entries)

### ISSUE THREAD

**Issue by filbranden** [igrigorik/vimgolf#319]
While testing #318 I bumped into this issue. Not sure if it's related to the implementation in #318 specifically (so potentially not an issue), or related to the upgrade of Ruby 2.4 -> 2.6 plus gems, or related to the MongoDB Atlas backend now being on version 4.2.

In any case, the issue is some data is triggering an "invalid UTF-8 data" exception.

Here's an example exception:

```
2021-04-07T19:19:56.884481+00:00 app[web.1]: MONGODB | vimgolf-shard-00-01-izmo5.gcp.mongodb.net:27017 req:138 | vimgolf.find | FAILED | String qqfai"$"�kd0q2@qZZ is not valid UTF-8: bogus initial bits | 0.328887064s
2021-04-07T19:19:56.885836+00:00 app[web.1]:   Rendered shared/_submissions.erb (493.0ms)
2021-04-07T19:19:56.886086+00:00 app[web.1]:   Rendered challenges/show.erb within layouts/application (1833.2ms)
2021-04-07T19:19:56.886342+00:00 app[web.1]: I, [2021-04-07T19:19:56.886272 #6]  INFO -- : Completed 500 Internal Server Error in 2093ms (MongoDB: 1.5ms)
2021-04-07T19:19:56.889176+00:00 app[web.1]:   
2021-04-07T19:19:56.889232+00:00 app[web.1]: ActionView::Template::Error (String qqfai"$"�kd0q2@qZZ is not valid UTF-8: bogus initial bits):
2021-04-07T19:19:56.889378+00:00 app[web.1]:     1: <% submissions.each do |solution| %>
2021-04-07T19:19:56.889378+00:00 app[web.1]:     2:   <div class="<%= submissions.highlight_owner? && solution.owner?(current_user) ? "note" : "success" %> clearfix">
2021-04-07T19:19:56.889379+00:00 app[web.1]:     3: 
2021-04-07T19:19:56.889379+00:00 app[web.1]:     4:   <h6 style="margin-bottom:0.5em">
2021-04-07T19:19:56.889431+00:00 app[web.1]:   
2021-04-07T19:19:56.889497+00:00 app[web.1]: app/repositories/repository_challenge.rb:263:in `submissions'
2021-04-07T19:19:56.889497+00:00 app[web.1]: app/services/submissions.rb:34:in `submissions'
2021-04-07T19:19:56.889497+00:00 app[web.1]: app/services/submissions.rb:20:in `each'
2021-04-07T19:19:56.889498+00:00 app[web.1]: app/views/shared/_submissions.erb:1:in `_app_views_shared__submissions_erb__124625788389501870_47454950052920'
2021-04-07T19:19:56.889498+00:00 app[web.1]: app/views/challenges/show.erb:19:in `_app_views_challenges_show_erb___2418147836399652034_47454947630640'
```

I caught this in my "staging" instance, while accessing challenge with id `5462e3f41198b80002512673` ("I forgot quotes") and it seems to reproduce consistently. I also saw similar exceptions (with longer strings that seem to bump out the "not valid UTF-8" part) in some other challenges.

Remains to be seen whether this needs a more thorough scrubbing of the data, if it's actually possible to reproduce it under situations other than #318 which will probably get scrapped...

cc @Hettomei

**Comment by Hettomei** [comment]
I also see that
Go to vimgolf.com
Open a very old challenge with few entries (less than 50)

I beleive this bug exist for a long time and that s why their is few entry.

**Comment by Hettomei** [comment]
Try http://www.vimgolf.com/challenges/51a388ac06f7d20002000006

**Comment by filbranden** [comment]
I dug into this one a little bit and I found that Ruby 2.4 vs Ruby 2.6 makes a difference here. The version of Mongoid doesn't seem to be relevant, downgrading Mongoid to 6.1.1 on Ruby 2.6 doesn't fix this.

Following the challenge mentioned by Hettomei above, I see which entry is causing the problem.

On Ruby 2.4, rails console:

```
irb(main):001:0> client = DatabaseHelper.client
irb(main):002:0> c = client[:challenges].find(_id: BSON::ObjectId('51a388ac06f7d20002000006'))
irb(main):003:0> c.first[:entries][0][:script]
D, [2021-04-25T17:08:11.253378 #887845] DEBUG -- : MONGODB | localhost:27017 | vimgolf.find | STARTED | {"find"=>"challenges", "filter"=>{"_id"=>BSON::ObjectId('51a388ac06f7d20002000006')}, "lsid"=>{"id"=><BSON::Binary:0x48703520 type=uuid data=0xcc37fac274314b02...>}}
D, [2021-04-25T17:08:11.257137 #887845] DEBUG -- : MONGODB | localhost:27017 | vimgolf.find | SUCCEEDED | 0.002626942s
=> "248@=n\x80kB212-ch\x80kB@\"))\x80\xFFXP'\u0002'/\\l\x80\xFFXx\"=\rZZ"
```

The same on Ruby 2.6 yields the following error:

```
D, [2021-04-25T16:58:06.829708 #887457] DEBUG -- : MONGODB | localhost:27017 req:9 conn:1:1 sconn:459 | vimgolf.find | STARTED | {"find"=>"challenges", "filter"=>{"_id"=>BSON::ObjectId('51a388ac06f7d20002000006')}, "$db"=>"vimgolf", "lsid"=>{"id"=><BSON::Binary:0x50232300 type=uuid data=0x2a4c2f090ec24a83...>}}
ZZ is not valid UTF-8: bogus initial bits | 0.000816372sDB | localhost:27017 req:9 | vimgolf.find | FAILED | String 248@=n�kB212-ch�kB@"))��XP''/\l��Xx"=
Traceback (most recent call last):
        2: from (irb):13
        1: from (irb):13:in `first'
ZZ is not valid UTF-8: bogus initial bits)))��XP''/\l��Xx"=
```

Actually, this affects the whole challenge document, not simply this one entry. So simply accessing `c.first` already causes a break here.

I'm guessing since that entry has a mix of `\x80`, `\xFF`, `\u0002` (Ctrl-B?), some of those (most likely the first few) are triggering an encoding error. I guess the right encoding here would be ASCII-8BIT? But not sure how to configure that here to prevent the issue...

**Comment by filbranden** [comment]
It turns out it *was* the gems. I didn't see it at first while only downgrading `mongoid`, but after also downgrading `mongo` and `bson` it worked again. I sent a PR to downgrade and fix them.
