### ISSUE TITLE
Twitter auth broken

### ISSUE THREAD

**Issue by huynhj93** [igrigorik/vimgolf#389]
![image](https://github.com/user-attachments/assets/493862d7-c3e9-4099-92b7-e574d0b4d7bf)

Since this morning, twitter auth stopped working for me. Also getting errors with general authentication: 
```
john@DESKTOP-E831AGQ:~/github/leetcode/vimgolf$ vimgolf put 9v006694339a0000000002e2
Downloading Vimgolf challenge: 9v006694339a0000000002e2
/home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/lib/vimgolf/challenge.rb:74:in `rescue in download': Uh oh, couldn't download or parse challenge, please verify your challenge id & client version. (RuntimeError)
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/lib/vimgolf/challenge.rb:40:in `download'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:95:in `put'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:44:in `start'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/bin/vimgolf:9:in `<top (required)>'
        from /home/john/.rbenv/versions/3.2.2/bin/vimgolf:25:in `load'
        from /home/john/.rbenv/versions/3.2.2/bin/vimgolf:25:in `<main>'
/home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/json_pure-2.6.3/lib/json/common.rb:216:in `parse': unexpected token at '<html><body>You are being <a href="https://www.vimgolf.com/">redirected</a>.</body></html>' (JSON::ParserError)
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/json_pure-2.6.3/lib/json/common.rb:216:in `parse'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/lib/vimgolf/challenge.rb:50:in `download'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:95:in `put'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:44:in `start'
        from /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vimgolf-0.5.0/bin/vimgolf:9:in `<top (required)>'
        from /home/john/.rbenv/versions/3.2.2/bin/vimgolf:25:in `load'
    ```

**Comment by diegobit** [comment]
It's the same for me, but with github auth, under docker:

```
docker run --rm -it -e "key=MY_KEY" ghcr.io/filbranden/vimgolf 9v0066c85bd8000000000324 
Downloading Vimgolf challenge: 9v0066c85bd8000000000324
Traceback (most recent call last):
	11: from /usr/local/bin/vimgolf:23:in `<main>'
	10: from /usr/local/bin/vimgolf:23:in `load'
	9: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/bin/vimgolf:9:in `<top (required)>'
	8: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:44:in `start'
	7: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	6: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	5: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	4: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	3: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:95:in `put'
	2: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/lib/vimgolf/challenge.rb:50:in `download'
	1: from /var/lib/gems/2.7.0/gems/json_pure-2.6.3/lib/json/common.rb:216:in `parse'
/var/lib/gems/2.7.0/gems/json_pure-2.6.3/lib/json/common.rb:216:in `parse': 783: unexpected token at '<html><body>You are being <a href="https://www.vimgolf.com/">redirected</a>.</body></html>' (JSON::ParserError)
	10: from /usr/local/bin/vimgolf:23:in `<main>'
	9: from /usr/local/bin/vimgolf:23:in `load'
	8: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/bin/vimgolf:9:in `<top (required)>'
	7: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:44:in `start'
	6: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	5: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	4: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	3: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	2: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/lib/vimgolf/cli.rb:95:in `put'
	1: from /var/lib/gems/2.7.0/gems/vimgolf-0.5.0/lib/vimgolf/challenge.rb:40:in `download'
/var/lib/gems/2.7.0/gems/vimgolf-0.5.0/lib/vimgolf/challenge.rb:74:in `rescue in download': Uh oh, couldn't download or parse challenge, please verify your challenge id & client version. (RuntimeError)
```

**Comment by diegobit** [comment]
I had this problem since yesterday, bot now I'm able to enter a challenge 🤷

**Comment by igrigorik** [comment]
Perhaps Twitter API blip. Seems to be a-ok now.
